name: Build and Release Kotlin APK

on:
  push:
    tags:
      - 'v*' 

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant Execute Permission to Gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Locate APK
        id: find_apk
        run: |
          ls -R app/build/outputs/apk/release/
          APK_FILE=$(find app/build/outputs/apk/release -name "*.apk" | head -n 1)
          echo "APK_PATH=$APK_FILE" >> $GITHUB_ENV
          echo "Found APK at: $APK_FILE"

      - name: Upload APK as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: ${{ env.APK_PATH }}
          compression-level: 0 
          if-no-files-found: error 

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download APK Artifact
        uses: actions/download-artifact@v4
        with:
          name: release-apk
          path: .
          merge-multiple: true  

      - name: Rename APK (Optional)
        run: |
          APK_FILE=$(ls *.apk | head -n 1)
          mv $APK_FILE kotlin-app-${{ github.ref_name }}.apk
          echo "Renamed APK to kotlin-app-${{ github.ref_name }}.apk"

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false

