name: Android APK Release

on:
  push:
    tags:
      - 'v*'  # Runs when a tag starting with 'v' (e.g., v1.0.0) is pushed

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'  # Change as needed

      - name: Grant Execute Permission to Gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Find APK Path
        id: find_apk
        run: echo "APK_PATH=$(find app/build/outputs/apk/release -name '*.apk' | head -n 1)" >> $GITHUB_ENV

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: ${{ env.APK_PATH }}

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Built APK
        uses: actions/download-artifact@v3
        with:
          name: release-apk
          path: .

      - name: Rename APK (Optional)
        run: mv *.apk my-app-${{ github.ref_name }}.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false
